#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2018.4.36f1"
#define UNITY_VERSION_DIGITS "2018.4.36"
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2018
#define UNITY_VERSION_MAJ 4
#define UNITY_VERSION_MIN 36
#define UNITY_IS_BETA 0
